server_name = "127.0.0.1:8008"

# Enables registration. If set to false, no users can register on this server.
allow_registration = true

# The local address that the server listens on.
[[listeners]]
address = "0.0.0.0:8008"

[db]
url = "postgres://postgres:root@localhost:5432/palpo_local" # Update with your database URL

[well_known]
# Palpo handles the /.well-known/matrix/* endpoints, making both clients and servers try to access palpo with the host
# server_name and port 443 by default.
server = "127.0.0.1:8008"
client = "http://127.0.0.1:8008"
