// @generated by Diesel, do not edit
// This file is automatically generated by the Diesel schema generator.
// To update, run: diesel migration generate

use diesel::table;
use diesel::allow_tables_to_appear_in_same_query;

// ===== Users Table =====
table! {
    users (name) {
        name -> Text,
        password_hash -> Nullable<Text>,
        salt -> Nullable<Text>,
        is_admin -> Bool,
        is_guest -> Bool,
        is_deactivated -> Bool,
        is_erased -> Bool,
        shadow_banned -> Bool,
        locked -> Bool,
        displayname -> Nullable<Text>,
        avatar_url -> Nullable<Text>,
        creation_ts -> BigInt,
        last_seen_ts -> Nullable<BigInt>,
        user_type -> Nullable<Text>,
        appservice_id -> Nullable<Text>,
        consent_version -> Nullable<Text>,
        consent_ts -> Nullable<BigInt>,
        consent_server_notice_sent -> Bool,
    }
}

// ===== Devices Table =====
table! {
    devices (device_id, user_id) {
        device_id -> Text,
        user_id -> Text,
        display_name -> Nullable<Text>,
        last_seen_ts -> Nullable<BigInt>,
        last_seen_ip -> Nullable<Text>,
        last_seen_user_agent -> Nullable<Text>,
        created_ts -> BigInt,
    }
}

// ===== User IPs Table =====
table! {
    user_ips (user_id, ip, last_seen_ts) {
        user_id -> Text,
        ip -> Text,
        last_seen_ts -> BigInt,
        device_id -> Nullable<Text>,
        user_agent -> Nullable<Text>,
    }
}

// ===== Room Memberships Table =====
table! {
    room_memberships (room_id, user_id) {
        room_id -> Text,
        user_id -> Text,
        membership -> Text,
        joined_ts -> Nullable<BigInt>,
        invite_ts -> Nullable<BigInt>,
        leave_ts -> Nullable<BigInt>,
        ban_ts -> Nullable<BigInt>,
    }
}

// ===== User Rate Limit Configs Table =====
table! {
    user_rate_limit_configs (user_id) {
        user_id -> Text,
        messages_per_second -> Integer,
        burst_count -> Integer,
        created_at -> BigInt,
        updated_at -> BigInt,
    }
}

// ===== Account Data Table =====
table! {
    account_data (user_id, data_type) {
        user_id -> Text,
        data_type -> Text,
        content -> Text,
        created_ts -> BigInt,
        updated_ts -> BigInt,
    }
}

// ===== User Attributes Table =====
table! {
    user_attributes (user_id) {
        user_id -> Text,
        shadow_banned -> Bool,
        locked -> Bool,
        deactivated -> Bool,
        erased -> Bool,
        password_changed_ts -> Nullable<BigInt>,
        last_force_reset_ts -> Nullable<BigInt>,
        expiry_ts -> Nullable<BigInt>,
        created_at -> BigInt,
        updated_at -> BigInt,
    }
}

// ===== User Threepids Table =====
table! {
    user_threepids (user_id, medium, address) {
        user_id -> Text,
        medium -> Text,
        address -> Text,
        validated_ts -> Nullable<BigInt>,
        added_ts -> BigInt,
    }
}

// ===== User External IDs Table =====
table! {
    user_external_ids (user_id, auth_provider, external_id) {
        user_id -> Text,
        auth_provider -> Text,
        external_id -> Text,
        created_ts -> BigInt,
    }
}

// ===== Join Relationships =====
allow_tables_to_appear_in_same_query!(
    users,
    devices,
    user_ips,
    room_memberships,
    user_rate_limit_configs,
    account_data,
    user_attributes,
    user_threepids,
    user_external_ids,
);