FROM complement-palpo-base

WORKDIR /work

COPY Cargo.toml Cargo.toml
COPY Cargo.lock Cargo.lock

# COPY target/debug/palpo palpo

COPY crates crates
COPY tests/complement/cargo-config.toml /usr/local/cargo/config.toml
RUN --mount=type=cache,target=/usr/local/cargo/registry \
    --mount=type=cache,target=/work/target \
    --mount=type=cache,target=/root/.cargo \
    cargo build \
    && cp target/debug/palpo palpo
    # && rm -rf target

COPY tests/complement/palpo.toml palpo.toml
COPY tests/complement/caddy.json caddy.json
COPY tests/complement/startup.sh startup.sh

ENV PALPO_DATABASE_URL="postgres://postgres:postgres@127.0.0.1:5432/palpo"
ENV PALPO_CONFIG=/work/palpo.toml
# ENV RUST_LOG="warn,palpo=info,palpo_core=warn,salvo=error"
ENV LOG_FORMAT=text

# RUN echo "log = \"warn,_=off,sled=off\"" >> palpo.toml
# RUN sed -i "s/listen_addr = \"127.0.0.1:8008\"/listen_addr = \"0.0.0.0:8008\"/g" palpo.toml
RUN PG_VERSION=$(ls /etc/postgresql/) && \
    sed -i "s%127.0.0.1/32            md5%127.0.0.1/32            trust%g" /etc/postgresql/${PG_VERSION}/main/pg_hba.conf && \
    # Bump up max conns for moar concurrency
    sed -i 's/max_connections = 100/max_connections = 2000/g' /etc/postgresql/${PG_VERSION}/main/postgresql.conf && \
    chmod +x /work/startup.sh

RUN PG_VERSION=$(ls /etc/postgresql/) && \
    pg_ctlcluster ${PG_VERSION} main start && \
    su - postgres -c "psql -c \"ALTER USER postgres WITH PASSWORD 'postgres';\"" && \
    su - postgres -c "createdb palpo"

EXPOSE 8008 8448

CMD ["/work/startup.sh"]
