import assert from 'node:assert/strict';
import { createServer } from 'node:net';
import { once } from 'node:events';
import { mkdirSync, writeFileSync } from 'node:fs';
import { createApp } from '../server.mjs';
import { Workflow } from '../lib/workflow.mjs';
import { fleetInput } from './fixture.mjs';
import { accountFixture } from './accounts.fixture.mjs';

const { chromium } = await import(process.env.PLAYWRIGHT_MODULE ?? 'playwright-core');
const reserve = createServer().listen(0, '127.0.0.1'); await once(reserve, 'listening');
const port = reserve.address().port; await new Promise(resolve => reserve.close(resolve));
const origin = `http://127.0.0.1:${port}`, f = accountFixture({ autoJoinBot: false });
const server = createApp({ service: f.service, publicOrigin: origin, accountConfig: f.config, startAccountWorker: false });
server.listen(port, '127.0.0.1'); await once(server, 'listening');
await server.accounts.tick(); f.joinAdmin();
const fleet = await f.service.create(fleetInput, '@admin:example.test', 'admin-secret');
await new Workflow(f.service).connect(fleet.id, '@owner:example.test', 'owner-secret');
const browser = await chromium.launch({ headless: true, ...(process.env.CHROME_EXECUTABLE ? { executablePath: process.env.CHROME_EXECUTABLE } : { channel: 'chrome' }) });
const page = await browser.newPage({ viewport: { width: 1280, height: 1100 } }), errors = [];
page.on('pageerror', error => errors.push(error.message));
const out = new URL('../test-results/accounts/', import.meta.url); mkdirSync(out, { recursive: true });
try {
  await page.goto(origin);
  await page.getByRole('button', { name: 'Request an account', exact: true }).click();
  const form = page.locator('#account-request-form');
  await form.getByLabel('Username', { exact: true }).fill('alice');
  await form.getByLabel('Display name').fill('Alice 张');
  await form.getByLabel('Choose a password', { exact: true }).fill('a-long-test-password-2026');
  await form.getByLabel('Confirm password').fill('a-long-test-password-2026');
  await form.getByLabel('Why would you like an account?').fill('Create a project and work with Agents.');
  await form.getByRole('button', { name: 'Send account request' }).click();
  await page.getByText(/Waiting for administrator approval/).waitFor();
  assert.equal(f.credentials.size, 0);
  const storage = await page.evaluate(() => localStorage.getItem('palpo.accountRequest.v1'));
  assert.ok(!storage.includes('password')); assert.ok(!storage.includes('a-long-test-password'));
  const { id } = JSON.parse(storage); await server.accounts.tick();
  const row = server.accounts.state.requests[id]; assert.equal(row.status, 'pending');
  await page.reload(); await page.getByRole('button', { name: 'Request an account', exact: true }).click();
  await page.getByText(/delivered to the private administrator room/).waitFor();
  await page.screenshot({ path: new URL('pending.png', out).pathname, fullPage: true });
  const verdict = f.decision(row); f.events.set(verdict.event_id, verdict);
  await server.accounts.tick(); await server.accounts.tick();
  await page.locator('#refresh-account-request').click(); await page.getByText(/Your account is ready/).waitFor();
  await page.screenshot({ path: new URL('approved.png', out).pathname, fullPage: true });
  await page.getByRole('button', { name: 'Sign in to your new account' }).click();
  assert.equal(await page.getByLabel('Matrix ID', { exact: true }).inputValue(), '@alice:example.test');
  await page.locator('#login-form').getByLabel('Password', { exact: true }).fill('a-long-test-password-2026');
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await page.locator('#member-workspace').waitFor({ state: 'visible' });
  assert.equal(await page.locator('#workspace').isVisible(), false);
  const project = page.locator('#project-form'); await project.getByLabel('Project name').fill('Alice project');
  await project.getByRole('button', { name: 'Create project and approval room' }).click();
  await page.locator('#projects').getByText('Owner approval: pending', { exact: true }).waitFor();
  await page.locator('#request-form').getByLabel('Agent name').fill('小白-01');
  const operationId = await page.locator('#request-form [name=requestId]').inputValue();
  const registeredProject = Object.values(f.store.state.projects).find(p => p.ownerMxid === '@alice:example.test');
  f.putState(f.rooms.get(registeredProject.ownerDmRoomId), 'm.room.member', '@approvalbot:example.test', { membership: 'join' }, '@approvalbot:example.test');
  await page.locator('#projects').getByText('Owner approval: ready', { exact: true }).waitFor();
  const requestForm = page.locator('#request-form');
  assert.equal(await requestForm.getByLabel('Agent name').inputValue(), '小白-01');
  assert.equal(await page.locator('#request-form [name=requestId]').inputValue(), operationId);
  await requestForm.getByLabel('Resource', { exact: true }).selectOption({ index: 1 });
  await requestForm.getByLabel('Agent name').fill('小白-01');
  assert.equal(await requestForm.getByLabel('Agent name').evaluate(el => el.checkValidity()), true);
  await requestForm.getByRole('button', { name: 'Send agent request' }).click();
  await page.waitForFunction(() => document.querySelector('#requests').textContent.includes('pending'));
  assert.equal(f.requests.size, 1); assert.equal([...f.requests.values()][0].state, 'pending');
  assert.equal([...f.requests.values()][0].agentDefinition.name, '小白-01');
  await page.screenshot({ path: new URL('project-agent-request.png', out).pathname, fullPage: true });
  await page.getByRole('button', { name: 'Sign out', exact: true }).click();
  await page.getByLabel('Matrix ID', { exact: true }).fill('@admin:example.test');
  await page.locator('#login-form').getByLabel('Password', { exact: true }).fill('correct-password');
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await page.getByRole('link', { name: 'Open account approval room in Robrix' }).waitFor();
  assert.ok((await page.locator('#account-admin-requests').innerText()).includes('registered'));
  assert.deepEqual(errors, []);
  writeFileSync(new URL('summary.json', out), JSON.stringify({ passed: true, realPalpo: false, nativeRobrix: false, pageErrors: errors,
    checks: ['signup form', 'password-free browser receipt', 'pending survives reload', 'Octos verdict received through room history', 'approved account login', 'ordinary member creates project', 'Agent request remains pending HAFleet approval', 'admin room link and request visibility'] }, null, 2));
  console.log('Account signup browser flow passed: signup → approval fixture → login → project → Agent request.');
} finally { await browser.close(); await server.accounts.stop(); await new Promise(resolve => server.close(resolve)); f.store.close(); }
