# =============================================================================
#  This is the official example config for Palpo.
#  If you use it for your server, you will need to adjust it to your own needs.
#  At the very least, change the server_name field!
# =============================================================================

# The server_name is the pretty name of this server. It is used as a suffix for user
# and room ids. Examples: matrix.org, palpo.im

# The Palpo server needs all /_matrix/ requests to be reachable at
# https://your.server.name/ on port 443 (client-server) and 8448 (federation).

# If that's not possible for you, you can create /.well-known files to redirect
# requests. See
# https://matrix.org/docs/spec/client_server/latest#get-well-known-matrix-client
# and
# https://matrix.org/docs/spec/server_server/r0.1.4#get-well-known-matrix-server
# for more information

# YOU NEED TO EDIT THIS
server_name = "your.server.name"

# Max size for uploads
max_upload_size = 128_000_000 # in bytes

# Enables registration. If set to false, no users can register on this server.
allow_registration = true

allow_check_for_updates = true

# Servers listed here will be used to gather public keys of other servers.
# Generally, copying this exactly should be enough. (Currently, Palpo doesn't
# support batched key requests, so this list should only contain Synapse
# servers.)
trusted_servers = ["matrix.org"]

enable_admin_room = true

# The local address that the server listens on.
[[listeners]]
address = "127.0.0.1:8008"

[logger]
format = "pretty" # pretty, json, compact
#max_concurrent_requests = 100 # How many requests Palpo sends to other servers at the same time
#level = "warn,state=warn,rocket=off,_=off,sled=off"

[db]
url = "postgres://postgres:root@127.0.0.1:5432/palpo_local"
pool_size = 1

[federation]
enable = true

[well_known]
# Palpo handles the /.well-known/matrix/* endpoints, making both clients and servers try to access palpo with the host
# server_name and port 443 by default.
# If you want to override these defaults, uncomment and edit the following lines accordingly:
server = "127.0.0.1:6006"
client = "http://127.0.0.1:6006"